name: build-jumpcutter

on:
  push:
    paths:
      - "jumpcutter/**"
      - ".github/workflows/build-jumpcutter.yml"
  pull_request:
    paths:
      - "jumpcutter/**"
      - ".github/workflows/build-jumpcutter.yml"
  workflow_dispatch:


jobs:
  build-jumpcutter:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/bagc-jumpcutter
          flavor: |
            latest=false
          tags: |
            type=ref,event=pr,prefix=pr-
            type=ref,event=branch,prefix=br-
            type=ref,event=tag,prefix=tag-
            type=sha,prefix=sha-,fromat=long
            type=raw,enable=${{ github.ref == 'refs/heads/main' }},value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up docker cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-
            buildx-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: jumpcutter
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        # TODO remove me. prevent the cache from growing infinitely
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
